server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
resilience4j:
  retry:
    instances:
      foo-bar:
        max-attempts: 5
logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
spring:
  application:
    name: ms01-book-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${MYSQL_DEFAULT_PORT:3311}/book_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&permitMysqlScheme=true
    username: ${ROOT_USER:root}
    password: ${ROOT_PASSWORD:example}
  jackson:
    default-property-inclusion: NON_NULL
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    url: jdbc:mysql://localhost:${MYSQL_DEFAULT_PORT:3311}/book_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&permitMysqlScheme=true
    user: ${ROOT_USER:root}
    password: ${ROOT_PASSWORD:example}
    baseline-on-migrate: true
management:
  tracing:
    sampling:
      probability: 1.0 # para enviar 100% da amostra
    propagation:
      type: w3c
    baggage:
      enabled: true
    enabled: true
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans # alterar o endereco do Zipkin

